// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAP85ECIikE5H2E3zcerUJiHm7ve7rVuZU',
    appId: '1:614936806249:web:8a1e9bac8f6048b90633f8',
    messagingSenderId: '614936806249',
    projectId: 'predict-app-authentication',
    authDomain: 'predict-app-authentication.firebaseapp.com',
    storageBucket: 'predict-app-authentication.appspot.com',
    measurementId: 'G-X0C3YZMHN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZrxUwDT7xGCCfqa7pFEk5peECU0YJSL4',
    appId: '1:614936806249:android:7d7884c09b8b38cb0633f8',
    messagingSenderId: '614936806249',
    projectId: 'predict-app-authentication',
    storageBucket: 'predict-app-authentication.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWOlULiSjlm2Pfkt_O2IBSXqhPI-6oV1g',
    appId: '1:614936806249:ios:77da4d5496154da70633f8',
    messagingSenderId: '614936806249',
    projectId: 'predict-app-authentication',
    storageBucket: 'predict-app-authentication.appspot.com',
    iosClientId: '614936806249-224sgs39l4ep5kro93ti9r5fclc4l9ui.apps.googleusercontent.com',
    iosBundleId: 'com.example.proto',
  );
}
